# Generated by Django 5.0.7 on 2024-07-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
